### ISSUE TITLE
Необработанная ошибка при внесении неверных координат

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/NumericDigitize_NG#2]
Если выбрать EPSG:4326,  и ввести например координаты: 999 999, то случатся необработанное исключение:

```
Traceback (most recent call last):
  File "/home/yellow/.qgis2/python/plugins/numericalDigitize_NG/numericalDigitize.py", line 164, in createGeom
    transformedPoint = xform.transform( point )
QgsCsException: прямая трансформация of
(17.435839, 17.435839)
PROJ.4:  +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0 +to  +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs
Ошибка: latitude or longitude exceeded limits
```

![image](https://cloud.githubusercontent.com/assets/1277422/6938216/683305f4-d86a-11e4-8915-656f13d29b37.png)
- Необходимо обрабатывать ошибки перепроицирования 
- Выдавать MessageBox.Critical с текстом в эксепшене (например тут: Ошибка: latitude or longitude exceeded limits)
- Если окно с вводом координат еще не закрыто возвращать фокус ему

**Comment by alisovenko** [comment]
Done
