### ISSUE TITLE
Объекты созданные плагином не пишутся в WFS слой NGW

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/NumericDigitize_NG#3]
Исходный слой в проекции 3857.
В QGIS добавляется через WFS сервис (например http://176.9.38.120/cl2/resource/31/wfs).
Ввод координат осуществляется в 4326. Координаты валидные - 10 10.

Если редактирование производить стандартными инструментами ввода - Добавление нового объекта, то слой сохраняется без ошибок.
Если же вводить с помощью сабжа, то объект добавляется в слой, но слой сохраняться не желает:

```
Не удалось внести изменения в слой fosc

Ошибки: ОШИБКА: не добавлен 1 объект.

  Ошибки источника:
      пустой ответ
```

**Comment by yellow-sky** [comment]
Есть подозрение, что объект генерируемый плагином имеет некорректные параметры (может координаты?)

**Comment by alisovenko** [comment]
Исправлено в 0.2.2
